server:
  port: 80

# 用于接口，服务降级
feign:
  hystrix:
    enabled: true

# 消费者(Eureka Client)不直接访问生产者(Eureka Client)获取服务，而是通过访问 Rureka Server 实现负载均衡(Ribbon Client)获取服务
eureka:
  client:
    # false 表示不向注册中心注册自己。
    register-with-eureka: false
    # 设置与 Eureka Server 交互的地址查询服务和注册服务依赖的地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/